version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      #- run:
      #    name: run tests
      #    command: |
      #      . venv/bin/activate
      #      python manage.py test

      #- store_artifacts:
      #    path: test-reports
      #    destination: test-reports

      - setup_remote_docker:
          version: 19.03.12
      #    docker_layer_caching: true

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          echo "$TAG" > /tmp/VERSION
          mkdir -vp ~/.docker/cli-plugins/
          curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
          chmod a+x ~/.docker/cli-plugins/docker-buildx
          docker buildx version
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker context create buildcontext
          docker buildx create buildcontext --use
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker buildx build --push -t cablespaghetti/k8s-sidecar-build:$TAG --platform linux/amd64,linux/arm64,linux/arm/v7 .

      - persist_to_workspace:
          root: /tmp
          paths:
            - VERSION

  test-k8s-1-16:
    machine: true
    environment:
      KIND_VERSION: v0.8.1
      K8S_VERSION: v1.16.9
    steps:
      - attach_workspace:
          at: /tmp/
      - checkout
      - run: |
          VERSION=`cat /tmp/VERSION`
          sed -i 's/SIDECAR_VERSION/'"$VERSION"'/g' .circleci/test/sidecar.yaml
          cat .circleci/test/sidecar.yaml
      - run:
          name: test-in-cluster
          command: .circleci/test-in-cluster.sh
          no_output_timeout: 3600

  test-k8s-1-17:
    machine: true
    environment:
      KIND_VERSION: v0.8.1
      K8S_VERSION: v1.17.5
    steps:
      - attach_workspace:
          at: /tmp/
      - checkout
      - run: |
          VERSION=`cat /tmp/VERSION`
          sed -i 's/SIDECAR_VERSION/'"$VERSION"'/g' .circleci/test/sidecar.yaml
          cat .circleci/test/sidecar.yaml
      - run:
          name: test-in-cluster
          command: .circleci/test-in-cluster.sh
          no_output_timeout: 3600

  test-k8s-1-18:
    machine: true
    environment:
      KIND_VERSION: v0.8.1
      K8S_VERSION: v1.18.8
    steps:
      - attach_workspace:
          at: /tmp/
      - checkout
      - run: |
          VERSION=`cat /tmp/VERSION`
          sed -i 's/SIDECAR_VERSION/'"$VERSION"'/g' .circleci/test/sidecar.yaml
          cat .circleci/test/sidecar.yaml
      - run:
          name: test-in-cluster
          command: .circleci/test-in-cluster.sh
          no_output_timeout: 3600

  deploy:
    docker:
      - image: circleci/python:3.7.8
    steps:
      - attach_workspace:
          at: /tmp/
      - checkout
      - setup_remote_docker:
          version: 19.03.12
      #    docker_layer_caching: true

      - run: |
          TAG=`cat /tmp/VERSION`
          mkdir -vp ~/.docker/cli-plugins/
          curl --silent -L "https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
          chmod a+x ~/.docker/cli-plugins/docker-buildx
          docker buildx version
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker context create buildcontext
          docker buildx create buildcontext --use
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          echo "FROM cablespaghetti/k8s-sidecar-build:$TAG" | docker buildx build --push -t cablespaghetti/k8s-sidecar:$TAG -t cablespaghetti/k8s-sidecar:latest --platform linux/amd64,linux/arm64,linux/arm/v7 -

workflows:
  version: 2
  test_deploy:
    jobs:
      - build
      - test-k8s-1-16:
          requires:
            - build
      - test-k8s-1-17:
          requires:
            - build
      - test-k8s-1-18:
          requires:
            - build
      - deploy:
          requires:
            - test-k8s-1-16
            - test-k8s-1-17
            - test-k8s-1-18
          filters:
            branches:
              only: master
